sudo: false
language: node_js
os:
  - linux
  # Turn windows on when it is out of beta mode in travis-ci
  # - windows

node_js:
  - "12"

install:
  # the prepare script run during install currently does clean-build
  - npm install

script:
  - npm --version
  # - npm test
